### ISSUE TITLE
Merge to sphinxcontrib upstream repository

### ISSUE THREAD

**Issue by dahlia** [jalaziz/sphinxcontrib-httpdomain#1]
Hi @jalaziz,

You seem did add [bottle](http://bottlepy.org/) support for `sphinxcontrib.autohttp`, and it looks great.  I want to merge your improvements into its upstream repository as a maintainer of the package.  Only problem to do it is just difference of SCM two repositories use, but I will pick up the changes from this repository with property authoring if you approve.

Thanks,
Hong Minhee

**Comment by jalaziz** [comment]
I certainly approve. I've been meaning to make some changes in the way the
docs are generated (mainly grouping urls that point to the same view), but
haven't had time to work on that.

Let me know how I can help!

**Comment by dahlia** [comment]
@jalaziz Thanks for your approve.  I finally merged your changes to the upstream.
- 98211f6c209e589077ecc498bb848dcabb59fe47 (git) is migrated to [`852a74e`](https://bitbucket.org/birkenfeld/sphinx-contrib/commits/852a74e5c0bb75ce9b1a5196cf9c9423f514b836) (hg).
- [`05274cb`](https://bitbucket.org/birkenfeld/sphinx-contrib/commits/05274cb7d93fd9be036c09c22c6741b0bb478e64) (hg) is a merge commit.
- [`8e964f4`](https://bitbucket.org/birkenfeld/sphinx-contrib/commits/8e964f49b92841f794e707af3e5850c289e0dbbb) (hg) moves the common parts from `sphinxcontrib/autohttp/__init__.py` to `sphinxcontrib/autohttp/common.py`.  Just a trivial change.
- [`a00876a`](https://bitbucket.org/birkenfeld/sphinx-contrib/commits/a00876a1cd427460d62de3ed7c21d591a857a2f5) (hg) adds changelog and docs for it.

**Comment by dahlia** [comment]
@jalaziz `sphinxcontrib-httpdomain` 1.1.9, which includes this patch, is just released!  See [PyPI](https://pypi.python.org/pypi/sphinxcontrib-httpdomain/1.1.9) and [changelog](http://pythonhosted.org/sphinxcontrib-httpdomain/#version-1-1-9).  Thanks!
