### ISSUE TITLE
Flask blueprints cannot contain dots

### ISSUE THREAD

**Issue by emosbaugh** [jalaziz/sphinxcontrib-httpdomain#2]
https://github.com/jalaziz/sphinxcontrib-httpdomain/blob/master/sphinxcontrib/autohttp/flask.py#L95

blueprint, endpoint_internal = endpoint.split('.')

raises "ValueError: too many values to unpack"

**Comment by emosbaugh** [comment]
Patch below

https://gist.github.com/emosbaugh/9007011

**Comment by jalaziz** [comment]
@emosbaugh Sorry for the super late reply. The patch is best submitted directly to the sphinxcontrib project here: https://bitbucket.org/birkenfeld/sphinx-contrib

If you'd like. I can submit the patch on your behalf.

**Comment by emosbaugh** [comment]
@jalaziz submitted pr. thanks

https://bitbucket.org/birkenfeld/sphinx-contrib/pull-request/68/allow-dots-within-flask-blueprints

**Comment by jalaziz** [comment]
Closing since this was merged in upstream.
