### ISSUE TITLE
autobottle directive is failing for stable bottle version

### ISSUE THREAD

**Issue by sgala** [jalaziz/sphinxcontrib-httpdomain#3]
Since  commit https://github.com/defnull/bottle/commit/29abc97035fa6d172aa6fb7a745e2e63b12cb05e (part of 0.11.1) bottle Router.rules is not a dict, and thus autobottle fails with an exception. Current bottle stable is 0.12

**Comment by jalaziz** [comment]
Thanks for the heads up! I haven't used bottle in a while, so I haven't been following the changes. I'll try and get this updated soon.

**Comment by jalaziz** [comment]
@sgala Turns out this was fixed in the upstream version of sphinxcontrib. Check out https://bitbucket.org/birkenfeld/sphinx-contrib/commits/02c3a62fea0bde8778f185c18674a9c30a797ab0

I'm going to close this for now.
